### ISSUE TITLE
getFirstParagraph method in the Display class is too specific

### ISSUE THREAD

**Issue by flangfeldt** [neverwoods/bili#1]
The newly added method [Display::getFirstParagraph()](https://github.com/neverwoods/bili/blob/master/classes/Bili/Display.php#L209) in the [Display](https://github.com/neverwoods/bili/blob/master/classes/Bili/Display.php) class doesn't seem to be very usable outside of a very specific use-case. Going from there I don't think it should be part of the Bili framework and moved to the specific project's Utility class.

**Comment by rvanbaalen** [comment]
I have not a single clue in which project this is used so I would vote to get  this out either way. This isn't a very useful addition to the `Display` class indeed but removing it causes a potential breaking change.
