### ISSUE TITLE
Why is there a minDate and maxDate method on the Date class?

### ISSUE THREAD

**Issue by rvanbaalen** [neverwoods/bili#13]
See line 73 and 80. Seems very specific / opinionated for a generic utility class like Bili\Date, am I right?

**Comment by rvanbaalen** [comment]
Does it have something to do with this?

https://stackoverflow.com/questions/3953333/maximum-time-php

**Comment by flangfeldt** [comment]
If you want to work with valid dates for "modified since" queries the min. and max. date methods can help if you have an empty date. The dates in the methods are "official" dates in PHP.
