### ISSUE TITLE
FileIO::handleUpload() removing uploaded file if it does not match criteria

### ISSUE THREAD

**Issue by kaphert** [neverwoods/bili#14]
The `FileIO::handleUpload()` has a parameter to supply a list of allowed file extensions. Inside the method a check is being done on the file extension but that is it. The same happens with the max file size check. It only does a `die()` and that's it. 

Shouldnt' the files be removed if they do not match the criteria? There is also not an option to do it yourself after the upload has failed because of the use of `die()` instead of returning an error code. 

And the extension check could already be done before writing the files. The same probably for the file size check.

**Comment by flangfeldt** [comment]
Hi @kaphert, the method is meant to satisfy a specific implementation. Uploading of files with progress is a tricky thing with PHP, this method removes a lot of the hassle. The return value should be pushed directly to the client as it is a valid JSONP response. The client in turn can interpret the value and take necessary steps. 

I myself use the method together with Plupload, a great JS library for handling async uploads. I point the upload endpoint directly to an URL that is linked to the FileIO::handleUpload method.

I can provide you with a stripped code example of that specific setup if you want.

About the removal of "failed" files, you should always have logic in place that cleans temporary storage of uploaded files outside of the scripts that put them there.
