### ISSUE TITLE
Improve 'file exists' check in Display::html2pdf

### ISSUE THREAD

**Issue by rvanbaalen** [neverwoods/bili#4]
@flangfeldt shouldn't we improve this piece of code ([found here](https://github.com/neverwoods/bili/blob/master/classes/Bili/Display.php#L45))

``` php
        $blnCreated = exec($strExec);
        if (file_exists($strPdfFile)) {
            $varReturn = file_get_contents($strPdfFile);

            // Clean up
            @unlink($strHtmlFile);
            @unlink($strPdfFile);
        }
```

with this:

``` php
        $blnCreated = exec($strExec);
        if ($blnCreated && file_exists($strPdfFile)) {
            $varReturn = file_get_contents($strPdfFile);

            // Clean up
            @unlink($strHtmlFile);
            @unlink($strPdfFile);
        }
```

That way, the `$blnCreated` variable is used and if `exec` fails, `file_exists` doesn't even have to check for the file. Right now, the IDE marks `$blnCreated` as an unused variable.

Or could there be a situation where `exec` fails (e.g. returns `false`), but still creates a file? In that case, you still want the cleanup to happen.

**Comment by flangfeldt** [comment]
You always want the file_exists check. The response from exec is not enough to be sure the file has actually been created.

**Comment by flangfeldt** [comment]
We can remove $blnCreated all together. It's not relevant or checked.
